version: '3.7'

services:
  app:
    container_name: wayan_pastebin
    build: .
    command: uvicorn app.main:app --reload --host 0.0.0.0 --port 8000
    volumes:
      - ./:/app/
    ports:
      - 8000:8000
