"""description of changes

Revision ID: 96d08c0f2467
Revises: 
Create Date: 2023-02-18 14:55:11.381500

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '96d08c0f2467'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pastebin',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('paste_id', sa.String(length=50), nullable=False),
    sa.Column('url', sa.String(length=100), nullable=True),
    sa.Column('content', sa.String(length=256), nullable=True),
    sa.Column('expired_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('paste_id')
    )
    op.create_index(op.f('ix_pastebin_id'), 'pastebin', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_pastebin_id'), table_name='pastebin')
    op.drop_table('pastebin')
    # ### end Alembic commands ###
